### ISSUE TITLE
Add support for viewing screenshots (bin or extracted png)

### ISSUE THREAD

**Issue by gingerbeardman** [d0k3/CTRXplorer#2]
Add support for viewing screenshots (bin or png)

**Comment by d0k3** [comment]
This is possible if there is some functionality for that already in ctrulib, citra or ctrcommon. Anyone know about this are can provide an example?

**Comment by gingerbeardman** [comment]
These should help...

extract screenshots:
https://github.com/smealum/scrtool

read png:
https://github.com/ihaveamac/screenshot-merge

**Comment by d0k3** [comment]
SCRtool actually contains everything that is needed to read PNG files (the lodepng library), but not for showing the image onscreen.

As I wrote before, CTRXplorer is not intended as a media viewer, because adding in too much functionality might hurt stability. I can add this if it is in the standard libs, but not if I need to add external libraries.

**Comment by d0k3** [comment]
After checking ctrulib and citrus I decided to not add this feature. Beaing a media viewer goes beyound CTRXplorers scope. Still looking into the text viewer enhancement, though.

**Comment by gingerbeardman** [comment]
Fair enough, thanks for considering it
